const lyricsQuestions = [
  { hint: 'YOLO YOLO YO YO', answer: 'go' },
  { hint: 'Ayo ladies and gentlemennn', answer: 'dope' },
  { hint: 'baby you remind meee~ I want someone like you', answer: 'into the sun' },
  { hint: 'You know how we do do do do', answer: '2.0' },
  { hint: 'You can\'t stop me lovin myself', answer: 'idol' }
];

const roastLines = [
  'Even Loki couldn't trick people into thinking that was a great move.',
  'Tony Stark would invent a machine just to avoid your plan.',
  'Thanos snapped and somehow your luck disappeared too.',
  'Your idea is so wild even Spider-Man would swing away.',
  'If this were a comic, the villain would pause to laugh.',
  'The Avengers would agree that this is a dramatic plot twist.',
  'This feels like an overtime scene from a superhero blooper reel.',
  'Your energy is so chaotic even Hulk would take a breath.',
  'Black Panther would raise an eyebrow and say, "Try again."',
  'Your plan looks like it was written by an excited intern in the Baxter Building.',
  'Even Doctor Strange can't rewind to fix that choice.',
  'Your bravery is solid, your timing is just on a different planet.',
  'This is the kind of idea that makes aliens double-check their GPS.',
  'You have bold moves, but the suit still needs a little polish.',
  'If reality had an edit button, it would be pressed right now.',
  'Your enthusiasm is heroic, the execution is just on vacation.',
  'Someone call Jarvis, because your strategy needs a quick upgrade.',
  'Even Wakanda would nod politely and say, "Hmm."',
  'Your moment has cinematic flair, but the finale might be under review.',
  'Your storyline is dramatic, just not the blockbuster kind.',
  'That was a stunt worthy of an audition tape.',
  'Your spark is bright, your timing could use a tune-up.',
  'This feels like a tribute scene from a comic convention.',
  'You have universe-building vibes and charming chaos.',
  'Your confidence is legendary, your execution is adventurous.',
  'The heroes would arrive, roll their eyes, and then cheer you on.',
  'Even a flying car would slow down to watch this unfold.',
  'Your plan is powerful enough to inspire a sequel.',
  'That was bold enough to make a robot dance nervously.',
  'Your sense of theatrics is on point, the plan just needs less glitter.',
  'You're a magician of momentum, the ending is still loading.',
  'Your super move number 1 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 2 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 3 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 4 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 5 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 6 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 7 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 8 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 9 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 10 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 11 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 12 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 13 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 14 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 15 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 16 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 17 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 18 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 19 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 20 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 21 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 22 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 23 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 24 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 25 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 26 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 27 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 28 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 29 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 30 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 31 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 32 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 33 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 34 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 35 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 36 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 37 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 38 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 39 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 40 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 41 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 42 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 43 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 44 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 45 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 46 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 47 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 48 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 49 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 50 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 51 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 52 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 53 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 54 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 55 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 56 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 57 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 58 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 59 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 60 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 61 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 62 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 63 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 64 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 65 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 66 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 67 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 68 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 69 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 70 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 71 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 72 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 73 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 74 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 75 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 76 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 77 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 78 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 79 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 80 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 81 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 82 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 83 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 84 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 85 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 86 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 87 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 88 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 89 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 90 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 91 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 92 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 93 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
  'Your super move number 94 is wild and bright, but it still needs more hero polish.',
  'This sounds like a comic scene ready for a stronger encore.',
]

const moodBoostMessages = [
  'Keep your purple energy shining bright today!',
  'Your smile is the kind of sparkle that changes the day.',
  'You are capable of magic and midnight dreams.',
  'The universe just made space for your next big move.',
  'You have the glow of a star and the heart of a hero.',
  'Every small step today is part of your legendary story.',
  'Let that fearless energy lead you into a playful adventure.',
  'You are exactly the kind of bright spark this world needs.',
  'Your vibe makes the purple lights shine even brighter.',
  'Dream big, dance loud, and let the good moments find you.',
  'Today is a canvas painted with your boldest colors.',
  'Your curiosity is your superpower — unleash it.',
  'Even on quiet days, your heart is full of rhythm.',
  'You make the ordinary feel absolutely epic.',
  'The best surprises are waiting just around the next beat.',
  'You are a moving story, and every chapter is worth celebrating.',
  'Your energy is enough to light up the whole room.',
  'A little adventure is the perfect mood booster — you got this.',
  'Your good ideas are already on their way to a glow-up.',
  'You are worthy of kind words, bold dreams, and bright days.',
  'There is a spark in you that can turn any moment magical.',
  'Let your next step be playful, brave, and full of shine.',
  'You are the kind of person who turns purple into a celebration.',
  'Your spirit is powerful, and your smile is unstoppable.',
  'The world is ready for the energy you bring today.',
  'Your energy is a new chapter waiting to be written, line 1.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 2.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 3.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 4.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 5.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 6.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 7.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 8.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 9.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 10.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 11.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 12.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 13.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 14.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 15.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 16.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 17.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 18.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 19.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 20.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 21.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 22.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 23.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 24.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 25.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 26.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 27.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 28.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 29.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 30.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 31.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 32.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 33.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 34.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 35.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 36.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 37.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 38.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 39.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 40.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 41.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 42.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 43.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 44.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 45.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 46.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 47.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 48.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 49.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 50.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 51.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 52.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 53.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 54.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 55.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 56.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 57.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 58.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 59.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 60.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 61.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 62.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 63.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 64.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 65.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 66.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 67.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 68.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 69.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 70.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 71.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 72.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 73.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 74.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 75.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 76.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 77.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 78.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 79.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 80.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 81.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 82.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 83.',
  'Today is brighter because you are choosing to show up with heart.',
  'Your energy is a new chapter waiting to be written, line 84.',
  'Today is brighter because you are choosing to show up with heart.',
]

